packages/cli/src/run.ts, packages/swagger-ts/src/generators/TypeGenerator.ts, packages/swagger-zod/src/generators/ZodGenerator.ts, packages/ts-codegen/src/codegen.ts
- Support for x-enumNames in swagger-ts and swagger-zod
- CreateEnumDeclaration can now also accept number as value
=> fix: support for x-enumNames in swagger-ts and swagger-zod + createEnumDeclaration can now also accept number as value

.eslintrc.cjs, docs/pages/plugins/swagger-ts.mdx, examples/advanced/kubb.config.ts, examples/advanced/src/gen/models/ts/AddPetRequest.ts, examples/advanced/src/gen/models/ts/Order.ts, examples/advanced/src/gen/models/ts/Pet.ts, examples/advanced/src/gen/models/ts/petController/FindPetsByStatus.ts, packages/swagger-ts/src/builders/TypeBuilder.ts, packages/swagger-ts/src/generators/OperationGenerator.ts, packages/swagger-ts/src/generators/TypeGenerator.ts, packages/swagger-ts/src/types.ts, packages/ts-codegen/src/codegen.ts
`kubb.config.ts`
Added `asPascalConst` as new property for `enumType`. This will transform the name of the export to PascalCase instead of the default(`asConst`) that is using camelCase.
```typescript
import { defineConfig } from '@kubb/core'
export default defineConfig(() => {
return {
root: '.',
input: {
path: './petStore.yaml',
},
output: {
path: './src/gen',
clean: true,
},
hooks: {
done: ['npx eslint --fix ./src/gen', 'pnpm typecheck'],
},
plugins: [
['@kubb/swagger', { output: false, validate: true }],
[
'@kubb/swagger-ts',
{
enumType: 'asPascalConst', // can be 'enum' | 'asConst' | 'asPascalConst'
},
],
],
}
})
```
=> feat(swagger-ts): enumType `asPascalConst`

packages/cli/CHANGELOG.md, packages/core/CHANGELOG.md, packages/kubb/CHANGELOG.md, packages/swagger-client/CHANGELOG.md, packages/swagger-faker/CHANGELOG.md, packages/swagger-form/CHANGELOG.md, packages/swagger-swr/CHANGELOG.md, packages/swagger-tanstack-query/CHANGELOG.md, packages/swagger-ts/CHANGELOG.md, packages/swagger-zod/CHANGELOG.md, packages/swagger-zodios/CHANGELOG.md, packages/swagger/CHANGELOG.md, packages/ts-codegen/CHANGELOG.md
This release is too large to preview in the pull request body. View the full release notes here: https://github.com/kubb-project/kubb/blob/release-please--branches--main--release-notes/release-notes.md
=> chore: releasing Kubb

e2e/schemas/petStore.yaml, packages/core/src/utils/transformers/escape.test.ts, packages/core/src/utils/transformers/escape.ts, packages/core/src/utils/transformers/getEncodedText.test.ts, packages/core/src/utils/transformers/getEncodedText.ts, packages/core/src/utils/transformers/index.ts, packages/swagger-zod/src/generators/ZodGenerator.ts, packages/swagger-zodios/src/generators/OperationGenerator.ts
Schema
```yaml
Pet:
log:
type: string
maxLength: 42
minLength: 2
pattern: >-
^[A-Za-z0-9()\[\]'"][-A-Za-z0-9_.
\/()\[\]]{0,40}[A-Za-z0-9()\[\]'"]$
example: my_log_destination
```
```typescript
export const petSchema = z.object({
log: z.string().min(2).max(42).regex(new RegExp('%5E%5BA-Za-z0-9%28%29%5C%5B%5C%5D%27%22%5D%5B-A-Za-z0-9_.%20%5C/%28%29%5C%5B%5C%5D%5D%7B0%2C40%7D%5BA-Za-z0-9%28%29%5C%5B%5C%5D%27%22%5D%24')).optional()
})
expect(new RegExp('%5E%5BA-Za-z0-9%28%29%5C%5B%5C%5D%27%22%5D%5B-A-Za-z0-9_.%20%5C/%28%29%5C%5B%5C%5D%5D%7B0%2C40%7D%5BA-Za-z0-9%28%29%5C%5B%5C%5D%27%22%5D%24')).test('my_log_destination')).toBeTruthy()
// ^? false
```
```typescript
export const petSchema = z.object({
log: z.string().min(2).max(42).regex(new RegExp('^[A-Za-z0-9()\[\]'"][-A-Za-z0-9_. …
```
=> fix: proper escape Regex for Zod

packages/react-template/package.json, packages/react-template/tsup.config.ts, packages/swagger-client/tsup.config.ts, pnpm-lock.yaml
No impact on peerDependencies but increase in bundleSize
=> fix: include `react` and `react-reconciler` in the bundle

examples/advanced/src/gen/zodios.ts, examples/zodios/src/gen/zodios.ts, packages/swagger-zodios/src/generators/OperationGenerator.ts, packages/swagger/src/generators/OperationGenerator.ts, packages/swagger/src/types.ts
With a small change, it will generate the following(instead of using the full `Response` object):
**./zod/getUserSchema**
```
import { z } from 'zod'
export const getUserPathParamsSchema = z.object({ userId: z.string().describe(`Executes the action in the context of the specified user.`) })
/**
* @description Successful response
*/
export const getUserQueryResponseSchema = z.object({ message: z.string().optional(), user: z.object({ userId: z.string().optional() }).optional() })
```
**zodios.ts**
```
import { makeApi, Zodios } from '@zodios/core'
import { getUserQueryResponseSchema, getUserPathParamsSchema } from './zod/getUserSchema'
const endpoints = makeApi([
{
method: 'get',
path: '/users/:userId',
description: `...`,
requestFormat: 'json',
parameters: [
{
name: 'userId',
description: …
```
=> fix: correct parameters schema for `Zodios`(use of .shape and .schema.shape)

docs/plugins/swagger-client/index.md, docs/plugins/swagger-faker.md, docs/plugins/swagger-msw.md, docs/plugins/swagger-swr.md, docs/plugins/swagger-tanstack-query.md, docs/plugins/swagger-ts.md, docs/plugins/swagger-zod.md
noticed that some curly braces were causing blank text in the docs. i haven't tested this (apologies), but i assume escaping them should fix
=> docs: escape curly braces

packages/swagger-client/src/builders/ClientBuilder.tsx, packages/swagger-client/src/plugin.ts
- With the `clientImportPath` option coming in, copying the client.ts file is only necessary when using the `client` option, so I modified the conditional statement.
- The existing clientPath was a string type, so the check was unnecessary.
=> chore(swagger-client): copy client.ts only when the client options is provided

packages/swagger-zod/src/generators/ZodGenerator.ts
Fix unicode issue: 
https://stackoverflow.com/questions/68840457/can-i-use-the-unicode-flag-within-a-json-schema-pattern-regular-expression
=> Feat/zod add support unicode to regexp pattern 

packages/swagger-faker/src/parsers/fakerParser.test.ts, packages/swagger-faker/src/parsers/fakerParser.ts
OpenAPI schema with "nullable: true" generates incorrect js code like faker.string.alpha()null with @kubb/swagger-faker
It change it to something like faker.helpers.arrayElement([faker.string.alpha(),null])
=> feat: add support nullable to faker

packages/swagger-zodios/src/components/Definitions.tsx
Sometimes it is necessary to use a dynamic baseUrl in a single build.
In this case, it is necessary to create a `Zodios` instance externally, as shown in the example code below, and therefore it is necessary to export the necessary endpoints.
```ts
import { Zodios } from "@zodios/core";
import { endpoints } from '@generated-api/zodios'
const API_SERVER_URL = process.env.API_SERVER_URL
const myAPI = new Zodios(API_SERVER_URL, endpoints)
```
I also added getAPI, which allows you to create an API instance without endpoints import.
```ts
import { getAPI } from '@generated-api/zodios'
const myAPI = getAPI(process.env.API_SERVER_URL)
```
=> chore(swagger-zodios): export endpoints too

e2e/kubb.config.js, e2e/schemas/enums.yaml, packages/swagger-faker/mocks/enums.yaml, packages/swagger-faker/src/FakerGenerator.test.ts, packages/swagger-faker/src/FakerGenerator.ts, packages/swagger-faker/src/__snapshots__/FakerGenerator.test.ts.snap, packages/swagger-ts/mocks/enums.yaml, packages/swagger-ts/src/TypeGenerator.test.ts, packages/swagger-ts/src/TypeGenerator.ts, packages/swagger-ts/src/__snapshots__/TypeGenerator.test.ts.snap, packages/swagger-zod/mocks/enums.yaml, packages/swagger-zod/src/ZodGenerator.test.ts, packages/swagger-zod/src/ZodGenerator.ts, packages/swagger-zod/src/__snapshots__/ZodGenerator.test.ts.snap
=> feat: support x-enum-varnames

.changeset/little-walls-drop.md, docs/guide/cli.md, docs/plugins/cli/index.md, examples/advanced/package.json, packages/cli/bin/bkubb.cjs, packages/cli/bin/kubb.cjs, packages/cli/package.json, packages/cli/src/generate.ts, packages/cli/src/index.ts, packages/cli/src/utils/getSummary.ts, packages/core/src/types.ts, pnpm-lock.yaml
Kubb can be used with `Bun` but as explained here(https://bun.sh/docs/cli/bunx#shebangs) you need to set the _**shebang**_ to Bun. Because we want to support Node and Bun we cannot change this. So another bin has been added: `bkubb` that fully uses Bun.
Previously, to use `Kubb` with `bun` you need to use the following command:
```bash
bun node_modules/@kubb/cli/bin/kubb.js generate
```
That is of course not easy for an end user so we added a new CLI flag `--bun` that will call `bkubb` in the background so you can use the full power of `Bun`.
```bash
kubb --bun generate
```
Issue: https://github.com/oven-sh/bun/issues/5362
=> fix: support for bun

.changeset/thirty-cobras-push.md, examples/vue-query-v5/tsconfig.json, packages/swagger-ts/src/components/OperationSchema.tsx, packages/swagger/src/OperationGenerator.ts
Based on https://github.com/readmeio/oas/blob/9a630a410011db1a88dab2dd1fb95d541002be10/packages/oas/src/operation/index.ts#L598
=> Refactor and creation of `getResponseBody`

packages/parser/src/factory.ts
```
[  Error: Negative numbers should be created in combination with createPrefixUnaryExpression
- typescript.js:21097 Object.createNumericLiteral
[app]/[parser]/[typescript]/lib/typescript.js:21097:13
- factory.ts:461 
[app]/[@kubb]/parser/src/factory.ts:461:45
- Array.map
- factory.ts:457 Module.createEnumDeclaration
[app]/[@kubb]/parser/src/factory.ts:457:20
- typeParser.ts:312 
[app]/[@kubb]/swagger-ts/src/typeParser.ts:312:20
- Array.forEach
- typeParser.ts:310 typeParser
[app]/[@kubb]/swagger-ts/src/typeParser.ts:310:17
- SchemaGenerator.tsx:48 SchemaGenerator2.getSource
[app]/[@kubb]/swagger-ts/src/SchemaGenerator.tsx:48:24
- Schema.tsx:146 Component
[app]/[@kubb]/swagger/src/components/Schema.tsx:146:28
- react-reconciler.development.js:7478 renderWithHooks …
```
=> Fix "Error: Negative numbers should be created in combination with createPrefixUnaryExpression factory."

.changeset/smooth-camels-fold.md, packages/plugin-oas/src/SchemaGenerator.ts, packages/swagger-ts/mocks/enums.yaml, packages/swagger-ts/mocks/enums_2.0.yaml, packages/swagger-ts/src/SchemaGenerator.test.tsx, packages/swagger-ts/src/__snapshots__/SchemaGenerator.test.tsx.snap, packages/swagger-zod/mocks/enums3_1.yaml
Fixes #1030 
According to the [3.0 docs](https://swagger.io/docs/specification/data-models/enums/) and [this FAQ](https://github.com/OAI/OpenAPI-Specification/blob/main/proposals/2019-10-31-Clarify-Nullable.md#if-a-schema-specifies-nullable-true-and-enum-1-2-3-does-that-schema-allow-null-values-see-1900), an enum is nullable when both it's type is nullable and when null is a member of the enum. Currently kubb will crash with a null member, so this PR fixes this case.
I added a couple of test cases as well, but let me know if there are more ways I should test this.
=> Mark enum as nullable for null enum members

.changeset/kind-lions-check.md, packages/swagger-tanstack-query/src/components/Mutation.tsx, packages/swagger-tanstack-query/src/components/MutationImports.tsx, packages/swagger-tanstack-query/src/components/Query.tsx, packages/swagger-tanstack-query/src/components/QueryImports.tsx, packages/swagger-tanstack-query/src/components/QueryOptions.tsx, packages/swagger-tanstack-query/src/utils.ts, pnpm-lock.yaml
If you have multiple @tanstack packages in your package.json file, the logic that checks if your are using v5 will fail because internally is calling `isValidSync(/@tanstack/, '>=5')`
Call `isValidSync` explicitly passing `@tanstack/react-query`
=> Fix react-query dependency lookup

.changeset/moody-gorillas-sing.md, docs/plugins/swagger-client/index.md, docs/plugins/swagger-faker/index.md, docs/plugins/swagger-msw/index.md, docs/plugins/swagger-swr/index.md, docs/plugins/swagger-tanstack-query/index.md, docs/plugins/swagger-ts/index.md, docs/plugins/swagger-zod/index.md, examples/typescript/kubb.config.ts, examples/typescript/src/gen/ts/models/AddPetRequest.ts, examples/typescript/src/gen/ts/models/Pet.ts, packages/swagger-faker/src/types.ts, packages/swagger-ts/src/OperationGenerator.test.tsx, packages/swagger-ts/src/SchemaGenerator.test.tsx, packages/swagger-ts/src/components/OperationSchema.test.tsx, packages/swagger-ts/src/components/Schema.test.tsx, packages/swagger-ts/src/components/Schema.tsx, packages/swagger-ts/src/parser/index.ts, packages/swagger-ts/src/plugin.ts, packages/swagger-ts/src/types.ts, packages/swagger-zod/src/types.ts
Defining a custom mapper for TypeScript cannot work with strings(behind the scenes we are using the TypeScript factory, see https://www.kubb.dev/plugins/parser-ts/).
Most of the time, the OpenAPI file is incorrect and needs a change(manually or the provider made a mistake and needs to update the OpenAPI file) but in some cases, you want to override the generated type. 
To make that possible I added the `mapper` functionality like we have been using for `zod` and `faker` with one change: you need to return a `PropertySignature`(see `factory.createPropertySignature`).
> Use https://ts-ast-viewer.com/#code/C4TwDgpgBAKhDOwoF4oG8BQVtQMYENgIBzAewCcQB+ALikXIEsA7YjAXyA as an example of how to return the factory code from a TypeScript file.
```
import { defineConfig } from '@kubb/core'
import { …
```
=> Ts-plugin with custom mapper(experimental)

.changeset/popular-tigers-float.md, packages/swagger-zodios/src/OperationGenerator.test.tsx, packages/swagger-zodios/src/OperationGenerator.tsx, packages/swagger-zodios/src/__snapshots__/OperationGenerator.test.tsx.snap, packages/swagger-zodios/src/components/Definitions.tsx, packages/swagger-zodios/src/plugin.ts, packages/swagger-zodios/src/types.ts
Just a quick idea backwards compatible idea to make zodios slightly more friendly. This allows for `apiClient.someOperationId()` instead of `apiClient.path("/something/:id/nested/path/thing", {})`.
=> feat(swagger-zodios): add support for includeOperationIdAsAlias option

packages/swagger-msw/src/components/Operations.tsx
When the package is of type "module", all imports must have a file extension. The msw plugin currently does not include the `extName` when generating operations files.
=> bugfix(msw): including extName when generating operations files

packages/plugin-msw/src/generators/handlersGenerator.tsx
When a package is of type `module`, imports must have file extensions. The MSW plugin is not generating file extensions when creating the handlers files to re-export other generated files.
=> fix(msw): add missing extName to imports when generating operations files

.changeset/sweet-grapes-listen.md, packages/plugin-oas/src/SchemaGenerator.ts
`type: "null"` is a valid type in OAS 3.1, but this line will result in a warning if it's used.
=> Include 'null' in list of valid types

examples/advanced/src/gen/mocks/petController/createUploadFile.ts, examples/msw/src/gen/mocks/petMocks/createUploadFile.ts, packages/plugin-faker/src/parser/__snapshots__/index.test.ts.snap, packages/plugin-faker/src/parser/index.ts
Looks like the [faker image docs](https://fakerjs.dev/api/image#url) indicate the correct call is `url()` instead of `imageUrl()`?
=> fix: update faker.image.imageUrl to faker.image.url

.changeset/thirty-tomatoes-change.md, docs/changelog.md, packages/core/src/transformers/stringify.ts, packages/parser-ts/src/factory.ts, packages/plugin-faker/src/parser/__snapshots__/index.test.ts.snap, packages/plugin-oas/mocks/petStore.yaml, packages/plugin-oas/mocks/schemas.ts, packages/plugin-oas/src/SchemaGenerator.ts, packages/plugin-oas/src/SchemaMapper.ts, packages/plugin-oas/src/__snapshots__/SchemaGenerator.test.ts.snap, packages/plugin-ts/src/parser/__snapshots__/index.test.ts.snap, packages/plugin-ts/src/parser/index.ts, packages/plugin-zod/mocks/enums3_1.yaml, packages/plugin-zod/src/generators/__snapshots__/enumBooleanLiteral.ts, packages/plugin-zod/src/generators/__snapshots__/enumSingleLiteral.ts, packages/plugin-zod/src/generators/zodGenerator.test.tsx, packages/plugin-zod/src/parser/__snapshots__/index.test.ts.snap, packages/plugin-zod/src/parser/index.ts
``` [input]
enum:
type: boolean
enum:
- true
- false
```
becomes
``` [output]
z.enum(["true", "false"]) // [!code --]
z.union([z.literal(true), z.literal(false)]) // [!code ++]
```
=> fix: Enums should use `z.literal` when format is set to number, string, boolean

.changeset/poor-candles-wash.md, packages/plugin-oas/src/SchemaGenerator.ts
=> fix: add missing freeform object definition to plugin-oas schema generator

docs/plugins/core/index.md, docs/plugins/plugin-client/client.md, docs/plugins/plugin-oas/index.md, docs/plugins/plugin-react-query/index.md, docs/plugins/plugin-solid-query/index.md, docs/plugins/plugin-svelte-query/index.md, docs/plugins/plugin-vue-query/index.md
7e4f86a047c04dc889126875c1f2dd9d6e8fa47c Update link to plugin-client `client.ts` source code
03b8b83dcdea0ff698defc9adc87ed1c21dc789e Update docs according to #993
87d99c83aa35e1371c27f54deebeeb7a8b35bd3a Update docs according to #1132
e8a46f60efd6965f561307ebf715a4590eafbdbf Update links to TanStack Query docs
=> Update links to TanStack Query docs and change some links according to previous changes/renamings

.changeset/selfish-teachers-rhyme.md, packages/plugin-zod/src/components/Zod.tsx
=> fix: discard optional if default is present

docs/getting-started/at-glance.md
I noticed a small bug in the documentation. The link and the title of KOPER were switched.
=> docs: Update external link to the github page of KOPER.

.changeset/seven-grapes-leave.md, packages/oas/package.json, pnpm-lock.yaml
`oas` v24 depends on a version of `path-to-regexp` that has a security advisory: https://github.com/advisories/GHSA-9wv6-86v2-598j
The tests pass locally for me, and the [diff between v24 and v25](https://github.com/readmeio/oas/compare/oas%4024.9.0...oas%4025.0.1) looks harmless.
=> fix: Update oas to address path-to-regexp advisory

.changeset/good-zebras-know.md, packages/react/package.json, pnpm-lock.yaml
`ws` has a high severity CVE (https://github.com/advisories/GHSA-3h5v-q93c-6h6q), but kubb pins to a vulnerable version. So this loosens up the version constraint to allow patched versions.
=> fix: Loosen up ws dependency version constraint

packages/plugin-oas/mocks/petStore.yaml, packages/plugin-oas/src/SchemaGenerator.test.ts, packages/plugin-oas/src/SchemaGenerator.ts, packages/plugin-oas/src/__snapshots__/SchemaGenerator.test.ts.snap, packages/plugin-zod/mocks/petStore.yaml, packages/plugin-zod/src/generators/__snapshots__/toy.ts, packages/plugin-zod/src/generators/zodGenerator.test.tsx
=> Allow nullable with default null option

docs/tutorials/basic.md
Update `kubb` v3 basic tutorial to use `generators: []` instead of `output: false`.
=> docs: update plugin-oas no output config in basic tutorial

.changeset/chatty-rats-warn.md, packages/plugin-faker/src/components/Faker.tsx, packages/plugin-faker/src/generators/__snapshots__/createPet.ts, packages/plugin-faker/src/generators/__snapshots__/createPetSeed.ts, packages/plugin-faker/src/generators/__snapshots__/createPetUnknownTypeAny.ts, packages/plugin-faker/src/generators/__snapshots__/getPets.ts, packages/plugin-faker/src/generators/__snapshots__/pet.ts, packages/plugin-faker/src/generators/__snapshots__/petWithDateString.ts, packages/plugin-faker/src/generators/__snapshots__/petWithDayjs.ts, packages/plugin-faker/src/generators/__snapshots__/petWithMapper.ts, packages/plugin-faker/src/generators/__snapshots__/petWithRandExp.ts, packages/plugin-faker/src/generators/__snapshots__/pets.ts, packages/plugin-faker/src/generators/__snapshots__/showPetById.ts
Following #1548 to update the return type from `Partial<T>` to `T`.
=> fix: returnType for faker functions

.changeset/wicked-ligers-repair.md, packages/plugin-oas/src/OperationGenerator.ts
This patch fixes an issue where the `include` and `exclude` options only check for the first tag on a path. Instead, we should match on any tag.
Ex: Including the "public" tag will now include any path that has the "public" tag, even if it has other tags.
Ex: Excluding the "public" tag will now exclude any path that has the "public" tag, even if it has other tags.
=> fix(plugin-oas): matchers check for any tag

.changeset/dirty-games-unite.md, packages/plugin-client/clients/fetch.ts
Improving the last PR even more with Partial type for setConfig method
=> make setConfig method in fetch.ts client non-required with Partial type

docs/plugins/plugin-zod/index.md
Without `pluginTs`, you get the following error running `kubb generate` if you copy/paste the example:
```
ERROR  This plugin has a pre set that is not valid([               
"plugin-oas",
"plugin-ts"
]) (plugin: plugin-oas, hook: buildStart) (plugin: plugin-oas, hook: buildStart)
```
=> Add missing plugin to Zod plugin example

packages/plugin-react-query/src/components/InfiniteQuery.tsx, packages/plugin-react-query/src/components/InfiniteQueryOptions.tsx, packages/plugin-react-query/src/generators/infiniteQueryGenerator.tsx
Official builds of `@kubb/plugin-react-query` still emit infinite-query hooks that target the old TanStack overloads where
`TQueryData` doubles as `TPageParam`. With TanStack Query v5 (and the current `@tanstack/react-query` types), those signatures now require a distinct `TPageParam`, so consumers hit `TS2769` when `pageParam` isn’t a `number`.
This change updates the plugin to:
- Emit `InfiniteQuery` hooks with explicit `TQueryFnData`, `TError`, `TData`, `TQueryKey`, and `TPageParam` generics (defaulting
`TPageParam` to the configured query param type or `number`).
- Mirror the same generics in `InfiniteQueryOptions`, so the builder returns options keyed by the correct page-param type.
- Pass the configured `queryParam` from the generator into `InfiniteQuery`, letting the emitter pick …
=> fix(plugin-react-query): align infinite query generics with tanstack
